/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kubernetes.client.examples.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1ObjectMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ConfigClient is the Schema for the springs API
 */
@ApiModel(description = "ConfigClient is the Schema for the springs API")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2020-12-04T15:50:40.049Z[Etc/UTC]")
public class V1ConfigClient implements io.kubernetes.client.common.KubernetesObject {

	public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";

	@SerializedName(SERIALIZED_NAME_API_VERSION)
	private String apiVersion;

	public static final String SERIALIZED_NAME_KIND = "kind";

	@SerializedName(SERIALIZED_NAME_KIND)
	private String kind;

	public static final String SERIALIZED_NAME_METADATA = "metadata";

	@SerializedName(SERIALIZED_NAME_METADATA)
	private V1ObjectMeta metadata = null;

	public static final String SERIALIZED_NAME_SPEC = "spec";

	@SerializedName(SERIALIZED_NAME_SPEC)
	private V1ConfigClientSpec spec;

	public static final String SERIALIZED_NAME_STATUS = "status";

	@SerializedName(SERIALIZED_NAME_STATUS)
	private V1ConfigClientStatus status;

	public V1ConfigClient apiVersion(String apiVersion) {

		this.apiVersion = apiVersion;
		return this;
	}

	/**
	 * APIVersion defines the versioned schema of this representation of an object.
	 * Servers should convert recognized schemas to the latest internal value, and may
	 * reject unrecognized values. More info:
	 * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	 * @return apiVersion
	 **/
	@Override
	@javax.annotation.Nullable
	@ApiModelProperty(
			value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

	public String getApiVersion() {
		return apiVersion;
	}

	public void setApiVersion(String apiVersion) {
		this.apiVersion = apiVersion;
	}

	public V1ConfigClient kind(String kind) {

		this.kind = kind;
		return this;
	}

	/**
	 * Kind is a string value representing the REST resource this object represents.
	 * Servers may infer this from the endpoint the client submits requests to. Cannot be
	 * updated. In CamelCase. More info:
	 * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	 * @return kind
	 **/
	@Override
	@javax.annotation.Nullable
	@ApiModelProperty(
			value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public V1ConfigClient metadata(V1ObjectMeta metadata) {

		this.metadata = metadata;
		return this;
	}

	/**
	 * Get metadata
	 * @return metadata
	 **/
	@Override
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1ObjectMeta getMetadata() {
		return metadata;
	}

	public void setMetadata(V1ObjectMeta metadata) {
		this.metadata = metadata;
	}

	public V1ConfigClient spec(V1ConfigClientSpec spec) {

		this.spec = spec;
		return this;
	}

	/**
	 * Get spec
	 * @return spec
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1ConfigClientSpec getSpec() {
		return spec;
	}

	public void setSpec(V1ConfigClientSpec spec) {
		this.spec = spec;
	}

	public V1ConfigClient status(V1ConfigClientStatus status) {

		this.status = status;
		return this;
	}

	/**
	 * Get status
	 * @return status
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1ConfigClientStatus getStatus() {
		return status;
	}

	public void setStatus(V1ConfigClientStatus status) {
		this.status = status;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1ConfigClient v1ConfigClient = (V1ConfigClient) o;
		return Objects.equals(this.apiVersion, v1ConfigClient.apiVersion)
				&& Objects.equals(this.kind, v1ConfigClient.kind)
				&& Objects.equals(this.metadata, v1ConfigClient.metadata)
				&& Objects.equals(this.spec, v1ConfigClient.spec) && Objects.equals(this.status, v1ConfigClient.status);
	}

	@Override
	public int hashCode() {
		return Objects.hash(apiVersion, kind, metadata, spec, status);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1ConfigClient {\n");
		sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
		sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
		sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
		sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
